flowchart LR
  subgraph Legend
  Tennant_Boundry
  Enviorments
  end
  subgraph Tennant
  direction TB
     subgraph Dev
     end
    subgraph Test
     end
    subgraph Production
     end
    subgraph Orchestrator
     end
  end

style Tennant fill:#ffffff,stroke:#f66,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Dev fill:#ffffff,stroke:#275912,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Test fill:#ffffff,stroke:#275912,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Production fill:#ffffff,stroke:#275912,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Orchestrator fill:#ffffff,stroke:#275912,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Legend fill:#ffffff,stroke:#000000,stroke-width:2px,color:#000000: 5 5
style Enviorments fill:#ffffff,stroke:#275912,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
style Tennant_Boundry fill:#ffffff,stroke:#f66,stroke-width:2px,color:#000000,stroke-dasharray: 5 5
